#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$commandFile = __DIR__.DIRECTORY_SEPARATOR."config".DIRECTORY_SEPARATOR."commands.yml";
$command = \Symfony\Component\Yaml\Yaml::parseFile($commandFile);
var_dump($command);exit;
$c = new \League\Container\Container();

foreach($command as $key=>$val){
    $c->add($key,$val['class'],$val['share']??false);
    if(isset($val['properties']) && is_array($val['properties'])){
        foreach($val['properties'] as $k=>$v){
            $c->get($key)->$k=$v;
        }
    }
    if($val['isCommand']??false){
        $map[$c->get($key)->getName()] = $val['class'];
    }
}

$application = new Application("ship",'2.0');

$commandLoader = new Symfony\Component\Console\CommandLoader\ContainerCommandLoader($c,$map);
$application->setCommandLoader($commandLoader);

$application->run();