http:
  class: Guzzle\client
Cmd\LoginCommand:
  class: Cmd\LoginCommand
  isCommand: true
Cmd\CreateOrderCommand:
  class: Cmd\CreateOrderCommand
  isCommand: true
Cmd\AutoCreateOrderCommand:
  class: Cmd\AutoCreateOrderCommand
  isCommand: true