<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/7/24
 * Time: 17:08
 */

namespace Cmd;


use GuzzleHttp\Client;
use Psr\Http\Message\RequestInterface;

class PROClient extends Client
{
    public $domain = 'http://promotion.ship.com/';

    public $token;

    static protected $instance;

    public function __construct()
    {
        $config['headers'] = $this->initHeader();
        $config['base_uri']= $this->domain;
        $config['verify'] = false;
        parent::__construct($config);
    }
    protected function initHeader(){
        $headers['Accept'] = 'application/json';
        $headers['Accept-Encoding'] = 'gzip, deflate, br';
        $headers['Accept-Language'] = 'zh-CN,zh;q=0.9';
        $headers['Connection'] = 'keep-alive';
        $headers['Content-Type'] = 'application/x-www-form-urlencoded';
        $headers['User-Agent'] = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36 SE 2.X MetaSr 1.0";
        return $headers;
    }

    /**
     * @return self
     */
    static public function instance(){
        if(!static::$instance){
            static::$instance = new static();
        }
        return static::$instance;
    }

    public function send(RequestInterface $request, array $options = [])
    {
        $response = parent::send($request, ['headers'=>['token'=>$this->token]]); // TODO: Change the autogenerated stub
        $response = json_decode($response->getBody()->getContents(),true);
        if($response['code']!=0){
            throw new \RuntimeException($response['msg'], $response['code']);
        }
        return $response['data'];
    }
}